version: '3.8'

services:
  api-gateway:
    image: gateway-service-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - documents-service
      - signatures-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - DOCUMENTS_SERVICE_URL=http://documents-service:8082
      - SIGNATURES_SERVICE_URL=http://signatures-service:8083
    networks:
      - backend

  auth-service:
    image: auth-service-image:latest
    ports:
      - "8083:8083"
    networks:
      - backend

  documents-service:
    image: document-service-image:latest
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
    networks:
      - backend

  signatures-service:
    image: signature-service-image:latest
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
    networks:
      - backend

networks:
  backend:
    driver: bridge

