version: '3.8'
services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  document-service:
    build: ./document-service
    container_name: document-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - user-service

  signature-service:
    build: ./signature-service
    container_name: signature-service
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    depends_on:
      - user-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - user-service
      - document-service
      - signature-service

networks:
  microservices-network:
    driver: bridge
