server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: document-service
          uri: http://localhost:8081
          predicates:
            - Path=/documents/**
          filters:
            - AuthenticationFilter

        - id: signature-service
          uri: http://localhost:8082
          predicates:
            - Path=/signatures/**
          filters:
            - name: AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**




  application:
    name: LOCAL-GATEWAY
